### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by robhicks** [AtomLinter/linter-stylint#11]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-stylint](https://github.com/AtomLinter/linter-stylint) package, v2.0.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/robhicks/.atom/packages/linter-stylint/lib/linter-stylint-provider.coffee:71

TypeError: undefined is not a function
  at /Users/robhicks/.atom/packages/linter-stylint/lib/linter-stylint-provider.coffee:71:55
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at BufferedNodeProcess.module.exports.BufferedProcess.handleError (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:251:20)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:240:24)
  at emitOne (events.js:77:13)
  at ChildProcess.emit (events.js:166:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1055:12)
  at child_process.js:1127:20
  at process._tickCallback (node.js:357:13)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "autocomplete",
      "file-type-icons",
      "turbo-javascript",
      "last-cursor-position"
    ],
    "followSymlinks": false,
    "audioBeep": false,
    "excludeVcsIgnoredPaths": false
  },
  "linter-stylint": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
Stylus, v1.0.0
Sublime-Style-Column-Selection, v1.3.0
atom-tsd, v0.9.0
atom-typescript, v4.6.11
auto-detect-indentation, v0.4.2
autocomplete-paths, v1.0.2
browser-plus, v0.0.23
file-icons, v1.5.8
filesize, v0.2.0
hide-files, v0.1.7
highlight-line, v0.11.0
highlight-selected, v0.10.1
jsformat, v0.9.0
language-ejs, v0.2.0
linter, v1.1.0
linter-jshint, v0.1.7
linter-stylint, v2.0.0
local-history, v3.2.3
monokai, v0.14.0
navigate, v0.1.6
package-cop, v0.2.10
project-manager, v1.15.10
svg-preview, v0.6.0
tabs-to-spaces, v0.11.0
tool-bar, v0.1.8

# Dev
No dev packages
```

**Comment by matthojo** [comment]
Do you have https://www.npmjs.com/package/stylint installed?

**Comment by robhicks** [comment]
Nope, just the list identified above.

**Comment by matthojo** [comment]
You curretly need to have the global Stylint module installed for this package to work. We are looking into bundling stylint with this package in #10.
